### ISSUE TITLE
Inecting CDI Beans

### ISSUE THREAD

**Issue by lujop** [ralscha/extdirectspring#136]
I plan to start developing applications using Sencha Framework and I found your library very clear and well enginered. The problem is that I would prefer the developments to be Java EE 7 based instead of Spring.

At first sight seems that removing Spring dependencies is a lot of work and we will lose maintenance of new features. But a very good compromise will be to leave all spring dependencies but work with CDI provided beans instead of Spring ones.

At airplane distance, from a not Spring competent pilot, it seems that using CDI beans could be and easy change changing the context.getBean from ExtDirectSpringUtil.invoke for proper CDI code. 

Do you think that this is more or less true? Or there are some details or other pieces that I haven't seen and the requeriment that ExtDirectMethods must be used in Spring beans is coupled at higher levels than simply bean providing?

If you could provide your opinion or some advise it will be greatly appreciated.

**Comment by ralscha** [comment]
The library depends on spring in a lot of places. For example the form post methods of extdirect are handled completely by Spring. extdirectspring only redirects the call to Spring.

[DirectJNgine](https://code.google.com/p/directjngine/) is the better library for CDI. They also have a JEE/CDI connector.

**Comment by lujop** [comment]
Thanks @ralscha. I had already found the DirectJNGine but initially discarded it as I've found your library superior in terms of maintenance, open source, running examples,..

I will have to work more on it to decide. There are a lot of other features that are absolute Spring delegated like forms that will require a complete reimplementation?
If you don't advise me with a big no I think I will try to change spring beans with cdi beans and see how it works or crash ;)
Because for me Spring dependencies are not a problem, is more that I want CDI beans to be first class citizens that manage the EXTJS calls.

**Comment by ralscha** [comment]
I don't have any CDI experience. So I don't can give you any advice.

The central part of the library is the RouterController. That's the component that receives the client requests and calls the annotated methods. A look at this class should give you an idea how much it depends on Spring.
https://github.com/ralscha/extdirectspring/blob/master/src/main/java/ch/ralscha/extdirectspring/controller/RouterController.java

**Comment by lujop** [comment]
Thank you very much @ralscha.
I looked at that class first, and at airplane distance looked fine to me, very clean and well enginered that always facilitate insertion points, althouth I doesn't have Spring experience.

I will try and let you know If I've a success history.
