### ISSUE TITLE
Changing Jackson object mapper naming strategy impacts API json

### ISSUE THREAD

**Issue by da-baranov** [ralscha/extdirectspring#137]
I have an Oracle database and often use the JdbcTemplate.query method which returns a List&lt;Map&lt;string, object&gt;&gt; as a result of database query. Each key in such a map is returned in upper case but in Javascript world camelcase and lowercase  are preferrable.
To convert the list to JSON in which all key are to be converted to lowercase I forced EDS to use custom Jackson object mapper with lowercase naming strategy:

    <bean id="objectMapper" class="my.custom.ObjectMapper" />
    <bean id="jsonHandler" class="ch.ralscha.extdirectspring.util.JsonHandler">
        <property name="mapper" ref="objectMapper" />
    </bean>

In such a case an API definition for a form post handler method looks like 

    {
      "name" : "saveSnippet",
      "len" : 0,
      "**formhandler**" : true
    }

instead of expected

    {
      "name" : "saveSnippet",
      "len" : 0,
      "**formHandler**" : true
    }

This causes an Exception with a message "this controller does not handle form posts" of form submit.
Is it possible to force API generator controller to use it's own dedicated Jackson object mapper?

**Comment by ralscha** [comment]
I think that is a good idea. I will start working on that.

**Comment by da-baranov** [comment]
Thank you very much, Ralph and a lot of thanks for your excellent library!
