### ISSUE TITLE
Store filter syntax

### ISSUE THREAD

**Issue by da-baranov** [ralscha/extdirectspring#138]
Hi Ralph,

I have a direct store defined as follows:

    store: {
        fields: ['scode', 'sname'],
            filters: [ {property: 'ncrn', value: 79402191, type: 'numeric', comparison: 'eq' }],
            autoLoad: true,
            proxy: {
                type: 'direct',
                directFn: vocabularyService.getValues,
                extraParams: {
                    view: 'v_prdseknd',
                    sort: 'scode'
                }
            }
        }

The ExtDirectStoreReadRequest object contains a numeric filter as expected. The problem is that the filter deserializes the "property" and "value" fields correctly but it seems to me that it cannot  correctly deserialize the "comparison" property so I always get null. The "operator" property won't get deserialize also.

    filters: [ {property: 'ncrn', value: 79402191, type: 'numeric', operator: '=' }],

**Comment by ralscha** [comment]
What version of extdirectspring do you use?

**Comment by da-baranov** [comment]
1.5.2

**Comment by ralscha** [comment]
Does filter.getRawComparison() return something? Or is this null as well?

**Comment by da-baranov** [comment]
It returns null. 
In the following code

      static Filter createFilter(Map<String, Object> jsonData, ConversionService conversionService) {

the jsonData map contains just two items: "property" and "value" and not "operator" or "comparison"

**Comment by ralscha** [comment]
Does the client send operator/comparison?

**Comment by da-baranov** [comment]
No :) It sends

    "filter":[{"property":"ncrn","value":79402191}]}]

Is this an ExtJS bug or I use wrong filter description syntax?

**Comment by ralscha** [comment]
Not sure. I never used filters like this. 
I know that extjs 5 no longer sends a type and instead of comparison it sends operator

Maybe it works when you add it to the extraParams
```
 extraParams: {
     filter: [ {property: 'ncrn', value: 79402191, type: 'numeric', comparison: 'eq' }],
     view: 'v_prdseknd',
     sort: 'scode'
}
```

**Comment by da-baranov** [comment]
Thanks a lot, it works :+1:
