### ISSUE TITLE
@ExtDirectMethod(value = STORE_READ, jsonView=) is ignored

### ISSUE THREAD

**Issue by zmitrok** [ralscha/extdirectspring#139]
I have a batch of ExtDirect method, and somewhere in the middle of that batch a method with a custom jsonView is invoked. RouterController.handleMethodCallsSequential() method uses the jsonView of the last DirectResponse in the batch, so the jsonView of all other methods, including the one with the custom jsonView, are ignored.

**Comment by zmitrok** [comment]
Worked around this by annotating all methods with jsonView annotation, but really, if jsonView annotation is allowed at the method level, then the RouterController should serialize the response of each method using that method's jsonView.

**Comment by ralscha** [comment]
Any chance you can test my change? 
It's in the 1.6.0-SNAPSHOT

**Comment by zmitrok** [comment]
Seems to work in 1.6.0-SNAPSHOT. Thanks!

**Comment by ralscha** [comment]
Thanks for the feedback. I will create a release tomorrow.
