### ISSUE TITLE
Static methods for ExtDirectStoreResult, ExtDirectFormLoadResult, ExtDirectFormPostResult, ExtDirectRawJsonStoreResult

### ISSUE THREAD

**Issue by mayras** [ralscha/extdirectspring#141]
It will be good for nice coding to have static methods for creation ExtDirectStoreResult, ExtDirectFormLoadResult, ExtDirectFormPostResult, ExtDirectRawJsonStoreResult, for example:

instead of:

return new ExtDirectStoreResult<>(cameraTypes);

place next:

return Results.createStoreResult(cameraTypes);

**Comment by ralscha** [comment]
With ExtDirectStoreResult
```
@ExtDirectMethod(ExtDirectMethodType.STORE_MODIFY)
	public ExtDirectStoreResult<Employee> update() {
		List<Employee> employees = .....
		ExtDirectStoreResult<Employee> result = new ExtDirectStoreResult<Employee>(
				employees );
		return result;
	}
```
with the new EdStoreResult and in a more concise style
```
	@ExtDirectMethod(ExtDirectMethodType.STORE_MODIFY)
	public EdStoreResult update() {
		List<Employee> employees = .....
		return EdStoreResult.success(employees);
	}
```

Both styles are supported. This way existing code does not have to be changed.

**Comment by ralscha** [comment]
New alternative result classes.  

ExtDirectFormLoadResult ---> EdFormLoadResult
ExtDirectFormPostResult ---> EdFormPostResult
ExtDirectRawJsonStoreResult ---> EdJsonStoreResult
ExtDirectStoreResult  ----> EdStoreResult
