### ISSUE TITLE
Problem with grid grouping

### ISSUE THREAD

**Issue by syno2flickr** [ralscha/extdirectspring#143]
Hello,

I found a bug in the class ParametersResolver (line 575).
The condition:
`key.equals("group") && value != null && value instanceof List`
returns always false because _value_ is a _Map_ (a _LinkedHashMap_) and not a _List_.

**Comment by ralscha** [comment]
Nice catch. Thanks for reporting the error.

This is an array in Ext JS 4, but in 5 and 6 it is an object

4: ```group: [{property: "cuisine", direction: "ASC"}]```

5 + 6: ```group:{property: "cuisine", direction: "ASC"}```

**Comment by syno2flickr** [comment]
Thank you.
