### ISSUE TITLE
Test fail 

### ISSUE THREAD

**Issue by lugreen** [ralscha/extdirectspring#145]
Hi,
the lastest version test fail：
Results :

Tests in error: 
  ApiControllerTest.testGroup1:226->testGroup1:267 ? IllegalArgument Invalid for...
  ApiControllerTest.testGroup1WithConfig:241->testGroup1:267 ? IllegalArgument I...
  ApiControllerWithConfigurationTest.testGroup1:261->testGroup1:304 ? IllegalArgument
  ApiControllerWithConfigurationTest.testGroup1WithConfig:277->testGroup1:304 ? IllegalArgument

Tests run: 607, Failures: 0, Errors: 4, Skipped: 0

**Comment by ralscha** [comment]
Hi
Interesting. I cannot reproduce it. 
It does work on my computer and and on [Travish](https://travis-ci.org/ralscha/extdirectspring)

**Comment by lugreen** [comment]
Hi
May be the problem caused by   localization  date format  settting,  see Picture1 below:
![picture1](https://user-images.githubusercontent.com/1725996/32132124-32902212-bbf0-11e7-9b6d-b568c0d1a560.png)

**Comment by ralscha** [comment]
Great catch. This is the problem. The parsing only works when the default Locale in the JVM is set to english.

I need to set the locale to english for these formatters. 
```
DateTimeFormatter fmt = DateTimeFormat
   .forPattern("EEE, dd MMM yyyy HH:mm:ss z").withLocale(Locale.ENGLISH);
```

**Comment by lugreen** [comment]
It's right now.
