### ISSUE TITLE
Model CURD method  metadata support

### ISSUE THREAD

**Issue by lugreen** [ralscha/extdirectspring#146]
Hi,
I  useD direct proxy on Model level, below is my model define :
![image](https://user-images.githubusercontent.com/1725996/32154795-16947480-bd6e-11e7-91b6-d1a1344f702b.png)
I want to creat a model using code below:
```
var project=Ext.create("Studio.model.Project")
project.save({
    failure: function(record, operation) {
        // do something if the save failed
    },
    success: function(record, operation) {
        // do something if the save succeeded
    },
    callback: function(record, operation, success) {
        debugger;
    }
```
The problem is that i the metadata can't  be submit to serverside.
I inspected the extdirect code and   found that the MedataParameter annotation only apply STORE_READ,STORE_MODIFY,TREE_LOAD method.
![image](https://user-images.githubusercontent.com/1725996/32155086-1ed9de8a-bd70-11e7-918f-2d923df2a170.png)

Is there a way to use metadata on  "Model Level CRUD"?
Thanks !

**Comment by ralscha** [comment]
Hi

All these methods you reference in your code are CRUD methods

read -> STORE_READ
create -> STORE_MODIFY
delete -> STORE_MODIFY
destroy -> STORE_MODIFY

You should not use directFn and api in one proxy object. 
directFn is a simple alternative for the api configuration

There is an online example that uses metadata
https://demo.rasc.ch/eds/extjs6classic/rowedit.html

```js
Ext.define('Person', {
		extend: 'Ext.data.Model',
		fields: [ 'lastName', 'firstName', 'id', 'street', 'city', 'state', 'zip' ],
		proxy: {
			type: 'direct',
			api: {
				read: person4Action.load,
				create: person4Action.create,
				update: person4Action.update,
				destroy: person4Action.destroy
			},
			extraParams: {
				test: true
			},
			metadata: {
				table: 'person',
				no: 1,
				no2: 3
			},
			writer: {
				writeAllFields: true
			}
		}
	});
```

```java
	@ExtDirectMethod(value = ExtDirectMethodType.STORE_READ)
	public List<Person> load(ExtDirectStoreReadRequest request, Boolean test,
			@MetadataParam Optional<String> table, @MetadataParam Optional<Integer> no,
			@MetadataParam(defaultValue = "defaultValue") String optional) {

	}

	@ExtDirectMethod(value = ExtDirectMethodType.STORE_MODIFY)
	public List<Person> create(List<Person> newPersons,
			@MetadataParam Optional<String> table) {

	}

	@ExtDirectMethod(value = ExtDirectMethodType.STORE_MODIFY)
	public List<Person> update(List<Person> modifiedPersons,
			@MetadataParam Optional<String> table) {


	}

	@ExtDirectMethod(value = ExtDirectMethodType.STORE_MODIFY)
	public void destroy(List<Person> destroyPersons,
			@MetadataParam Optional<String> table) {

	}
```

**Comment by lugreen** [comment]
Hi,
Thanks very much!
My model with metadata can  access the service method when annotated the method as  ExtDirectMethodType.STORE_READ .
I will   do more tests  .
