### ISSUE TITLE
Spring 5?

### ISSUE THREAD

**Issue by choweiyuan** [ralscha/extdirectspring#149]
Hi does this library support Spring 5?

**Comment by ralscha** [comment]
It should work fine. I use the current version (1.7.4) in a few production apps with Spring Boot 2.0.1
and I haven't encountered any problems so far. 

The demo site is also using Spring Boot 2.0.1
https://github.com/ralscha/extdirectspring-demo

**Comment by choweiyuan** [comment]
Ok thanks for the clarification 👍  Will close this
